export const en = {
  "dashboard.refresh": "Refresh overview",
  "planner.kind.plotline": "Plotline",
  "planner.kind.quest": "Quest",
  "planner.kind.event": "Event",
  "planner.kind.branch": "Branch",
  "planner.eventType.story": "Story event",
  "planner.eventType.encounter": "Encounter",
  "planner.eventType.puzzle": "Puzzle",
  "planner.branchType.decision": "Decision",
  "planner.branchType.condition": "Condition gate",
  "planner.branchType.random": "Random gate",
  "dashboard.title": "Campaign Planning",
  "dashboard.description": "A concise overview of plans worth keeping visible between games.",
  "dashboard.loading": "Checking planning data and workflow capabilities…",
  "dashboard.forbidden": "The DM Tools dashboard is available only to the effective DM.",
  "dashboard.error.title": "Planning data is unavailable",
  "dashboard.error.body": "Planning data could not be read. Recovery links remain available.",
  "dashboard.status.total": "Total",
  "dashboard.status.plotlines": "Plotlines",
  "dashboard.status.quests": "Quests",
  "dashboard.status.encounters": "Encounters",
  "dashboard.status.notes": "Marginalia",
  "dashboard.workflow.title": "Planning tools",
  "dashboard.workflow.body": "Edit directly, inspect relationships, or review an atomically imported structure.",
  "dashboard.workflow.label": "DM planning tools",
  "dashboard.planning.title": "Story Planner",
  "dashboard.planning.body": "Build nested plotlines, quests, events, branches, references, and consequences across focused canvases.",
  "dashboard.import.title": "Import Center",
  "dashboard.import.body": "Preview and atomically commit a generated planning document.",
  "dashboard.importMissing": "Planning import is currently unavailable. You can still edit plans directly.",
  "dashboard.importError": "Import-provider status could not be checked.",
  "dashboard.items.title": "Recently changed",
  "dashboard.empty.body": "No planning items are stored yet.",
  "dashboard.empty.action": "Create the first item",
  "dashboard.unnamed": "Untitled planning item"
} as const;
export const cs = {
  "dashboard.refresh": "Obnovit přehled",
  "planner.kind.plotline": "Dějová linka",
  "planner.kind.quest": "Úkol",
  "planner.kind.event": "Událost",
  "planner.kind.branch": "Větvení",
  "planner.eventType.story": "Dějová událost",
  "planner.eventType.encounter": "Střetnutí",
  "planner.eventType.puzzle": "Hádanka",
  "planner.branchType.decision": "Rozhodnutí",
  "planner.branchType.condition": "Podmínka",
  "planner.branchType.random": "Náhodná brána",
  "dashboard.title": "Plánování kampaně",
  "dashboard.description": "Stručný přehled plánů, které má smysl držet mezi hrami na očích.",
  "dashboard.loading": "Ověřuji plánovací data a dostupnost nástrojů…",
  "dashboard.forbidden": "Přehled Nástrojů PJ je dostupný jen v účinné roli PJ.",
  "dashboard.error.title": "Plánovací data nejsou dostupná",
  "dashboard.error.body": "Plánovací data se nepodařilo načíst. Odkazy pro obnovu zůstávají dostupné.",
  "dashboard.status.total": "Celkem",
  "dashboard.status.plotlines": "Dějové linky",
  "dashboard.status.quests": "Úkoly",
  "dashboard.status.encounters": "Střetnutí",
  "dashboard.status.notes": "Poznámky",
  "dashboard.workflow.title": "Plánovací nástroje",
  "dashboard.workflow.body": "Upravujte přímo, procházejte vazby nebo zkontrolujte atomicky importovanou strukturu.",
  "dashboard.workflow.label": "Nástroje plánování PJ",
  "dashboard.planning.title": "Plánovač příběhu",
  "dashboard.planning.body": "Tvořte vnořené dějové linky, úkoly, události, větvení, odkazy a následky na přehledných samostatných plátnech.",
  "dashboard.import.title": "Centrum importu",
  "dashboard.import.body": "Zobrazte náhled a atomicky uložte vygenerovaný plánovací dokument.",
  "dashboard.importMissing": "Import plánů nyní není dostupný. Plány můžete dál upravovat přímo.",
  "dashboard.importError": "Stav poskytovatele importu se nepodařilo ověřit.",
  "dashboard.items.title": "Nedávno změněné",
  "dashboard.empty.body": "Zatím nejsou uložené žádné plánovací položky.",
  "dashboard.empty.action": "Vytvořit první položku",
  "dashboard.unnamed": "Plánovací položka bez názvu"
} as const;
